Prog/heinrichlaszlo
ZodX/TaskManager-v2 pull request #27
Opened 2020-11-28 16:44 UTC by heinrichlaszlo

2020-11-28 20:26 UTC, ZodX commented
Please separate the code into different files such as: 

* `index.js`
* `index.css`

2020-11-28 20:27 UTC, ZodX requested changes
Please separate the code into different files such as: 

* `index.js`
* `index.css`

2020-12-05 12:54 UTC, Hurip approved these changes

2020-12-05 12:54 UTC, Hurip approved these changes

2020-12-05 16:27 UTC, closed without merging